---
header-includes:
    - \usepackage{needspace}
    - \usepackage{emoji}
    - \usetheme{Warsaw}
title: "Reverse proxy jako mechanizm izolacji aplikacji webowych"
author:
    - "Sebastian Kwaśniak"
    - "Anna Berkowska"
    - "Artur Binczyk"
    - ""
    - "Jerzy Szyjut"
    - "Damian Trowski"
date: ""
#geometry: margin=2cm
output:
    beamer_presentation:
        latex_engine: lualatex
        keep_tex: true
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Wstęp

Po co izolować aplikacje webowe?

- Ciężej o eskalację uprawnień
- Mitygacja ataków DDOS
- Uproszczenie zarządzania certyfikatami

# Terminacja SSL

Czym jest terminacja SSL?

Terminacja SSL (ang. SSL termination) to proces zakończenia szyfrowanej sesji SSL/TLS
na serwerze pośredniczącym, zanim ruch zostanie przekazany do docelowego serwera.

# Terminacja SSL

Kiedy następuje terminacja SSL?

To zależy...

# Reverse Proxy

Czym jest Reverse Proxy i czym się to różni od zwykłego Proxy?

# Reverse Proxy

Czym jest Reverse Proxy i czym się to różni od zwykłego Proxy?

W skrócie:

- Reverse Proxy: przekierowuje żądania od klientów do serwerów wewnętrznych
- Proxy: Od klientów wewnętrznych do zasobów zewnętrznych

# Jak działa Reverse Proxy

1. Odebranie żądania przez Reverse Proxy
2. Odczytanie kluczowych parametrów do routowania:
 - Nagłówki HTTP, w tym głównie "Host", w której jest domena do której chce połączyć się klient
 - Dla połączenia SSL/TLS odczytanie rozszerzenia SNI (Server Name Identification)
 - Metoda HTTP
3. Przekazanie żądanie do odpowiedniego serwera na podstawie parametrów

# Wady Reverse Proxy

- SPOF (single point of failure)
- Nie jest to prawdziwa izolacja
- Dodaje opóźnienie
- Większe koszta (wdrożenie, utrzymanie, zasobowe...)

# Brak izolacji

```{tikz}

\usetikzlibrary{shapes.geometric}

\begin{tikzpicture}[node distance=2cm, auto]
    % Nodes

    \node [draw, minimum width=2cm, minimum height=5cm] (server) {};
    \node [above of=server] (servername) {Serwer};
    \node [draw, node distance=1.0cm, below of=servername] (app1) {App 1};
    \node [draw, node distance=1.0cm, below of=app1] (app2) {App 2};
    \node [draw, node distance=1.0cm, below of=app2] (app3) {App 3};

    \node [draw=none, left of=server, minimum width=0.1cm, node distance=5cm] (arrows) {};

    \draw[->] (arrows.east) -- (server.west);
    \draw[->] ([yshift=0.5cm]arrows.east) -- (server.west);
    \draw[->] ([yshift=1.0cm]arrows.east) -- (server.west);
    \draw[->] ([yshift=-0.5cm]arrows.east) -- (server.west);
    \draw[->] ([yshift=-1.0cm]arrows.east) -- (server.west);

\end{tikzpicture}
```

# Izolacja

```{tikz}

\usetikzlibrary{shapes.geometric}

\begin{tikzpicture}[node distance=2cm, auto]
    % Nodes

    \node [draw, minimum width=2cm, minimum height=5cm] (proxy) {Proxy};

    \node [draw=none, left of=proxy, minimum width=0.1cm, node distance=5cm] (arrows) {};

    \draw[->] (arrows.east) -- (proxy.west);
    \draw[->] ([yshift=0.5cm]arrows.east) -- (proxy.west);
    \draw[->] ([yshift=1.0cm]arrows.east) -- (proxy.west);
    \draw[->] ([yshift=-0.5cm]arrows.east) -- (proxy.west);
    \draw[->] ([yshift=-1.0cm]arrows.east) -- (proxy.west);

    \node [draw, right of=proxy, node distance=5cm] (app2) {App 2};
    \node [draw, above of=app2] (app1) {App 1};
    \node [draw, below of=app2] (app3) {App 3};

    \draw[->] (proxy.east) -- (app1.west);
    \draw[->] (proxy.east) -- (app2.west);
    \draw[->] (proxy.east) -- (app3.west);

\end{tikzpicture}
```

# Jakie są opcje

- Nginx
- HAProxy
- Traefik
- Pingora

# Jakie są opcje c.d

- \color{green}Nginx \color{black} - solidny
- \color{black}HAProxy - solidny
- Traefik - meh
- \color{red}Pingora \color{black} - blazingly fast \emoji{rocket} \emoji{rocket}

# Jak to wyglądałoby w teorii

```{tikz}

\usetikzlibrary{shapes.geometric}

\begin{tikzpicture}[node distance=2cm, auto]
    % Nodes
    \node [draw, minimum width=2cm] (routing) {HAProxy};

    \node [draw=none, right of=routing, node distance=4cm] (app2) {};
    \node [draw, minimum width=2cm, above of=app2] (app1) {Web1};
    \node [draw, minimum width=2cm, below of=app2] (app3) {Web2} node[above] at (app3.north) {Terminacja SSL};

    \node [draw, diamond, minimum width=2cm, node distance=4cm, right of=app1] (web1) {web2.delira.pl};
    \node [draw, diamond, minimum width=2cm, node distance=4cm, right of=app3] (web2) {notes.delira.pl};

    % Arrows
    \draw[->] ([yshift=0.1cm]routing.east) -- node[midway, above, pos=0.5, font=\small] {Terminacja SSL} (app1.west);
    \draw[->] ([yshift=-0.1cm]routing.east) -- (app3.west);

    \draw[->] (app1.east) -- (web1.west);
    \draw[->] (app3.east) -- (web2.west);
\end{tikzpicture}
```

# Configi i inne

Nie pokazujemy tutaj configów bo za długie i tekst byłby tak mały że nic by nie było widać
